services:
  proxy:
    image: ghcr.io/openrings/skebob-proxy:latest
    build:
      dockerfile: ./docker/Dockerfile.prod.proxy
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    networks:
      - shared

  backend:
    image: ghcr.io/openrings/skebob-backend:latest
    build:
      dockerfile: ./docker/Dockerfile.prod.backend
    restart: unless-stopped
    networks:
      - shared

  prometheus:
    image: ghcr.io/openrings/skebob-prometheus:latest
    build:
      dockerfile: ./docker/Dockerfile.prod.prometheus
    restart: unless-stopped
    volumes:
      - ./data/prometheus:/prometheus
    networks:
      - shared

  minecraft:
    image: ghcr.io/openrings/skebob-minecraft:latest
    build:
      dockerfile: ./docker/Dockerfile.prod.minecraft
    restart: unless-stopped
    stdin_open: true
    tty: true
    ports:
      - target: 25565
        published: 25565
        protocol: tcp
      - target: 25565
        published: 25565
        protocol: udp
    environment:
      EULA: TRUE
      TYPE: PAPER
      VERSION: 1.21.4
      MEMORY: 4G
      MOTD: "Наш сайт: skebobmc.ru"
      ICON: /icon.png
      DIFFICULTY: hard
      MAX_PLAYERS: 10000
      SNOOPER_ENABLED: false
      SPAWN_PROTECTION: 0
      VIEW_DISTANCE: 24
      MODE: survival
      ONLINE_MODE: false
      SERVER_PORT: 25565
      SIMULATION_DISTANCE: 12
    volumes:
      - ./data/minecraft:/data
    networks:
      - shared

  database:
    image: mariadb:11.8
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: minecraft
    volumes:
      - ./data/database:/var/lib/mysql
    networks:
      - shared


networks:
  shared:
