FROM node:24-alpine3.22 AS builder

WORKDIR /build

COPY ./frontend/package*.json ./

RUN npm install

COPY ./frontend ./

RUN npm run build

FROM caddy:2.10-alpine AS runner

COPY ./docker/Caddyfile.prod /etc/caddy/Caddyfile
COPY --from=builder /build/dist /web/client
