FROM rust:1.88-alpine3.22 AS builder

WORKDIR /build

RUN apk add --no-cache build-base

COPY ./backend/Cargo.* ./
RUN mkdir src && echo "fn main() {}" > src/main.rs
RUN cargo build -r

COPY ./backend .
RUN touch src/main.rs
RUN cargo build -r

FROM alpine:3.22 AS runner

WORKDIR /app

COPY --from=builder /build/target/release/skebob-mc ./app

ENTRYPOINT ["./app"]

